### ISSUE TITLE
Incorrect PHY_ADR

### ISSUE THREAD

**Issue by Mobivlad** [ArtemBashtovyi/lab3#1]
https://github.com/ArtemBashtovyi/lab3/blob/59dd682b8607a8e4b52ace9d089870b274441dc6/Include/stm32f4x7_eth_bsp.h#L52

![image](https://user-images.githubusercontent.com/17147322/78148183-3b017600-743d-11ea-871a-cb397166c197.png)

**Comment by ArtemBashtovyi** [comment]
Thanks. Fixed in 96d2ba94d0b3272c7bb2928d157f2120a7e99169
